# SPDX-FileCopyrightText: 2026 rinbal
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Pins the private-file envelope to the format Lotus writes.

The point of this format is interoperability: a private file uploaded
from Lotus has to open here, and one written here has to open there. Any
change to the construction breaks that silently, because both sides
produce plausible-looking bytes either way and only fail when a real
user opens a real file.

So the format is pinned to a vector generated from the SAME WebCrypto
calls Lotus makes (crypto.subtle HKDF-SHA256 with salt=nonce and
info="nip44-v2", then AES-GCM). If that vector stops decrypting, the
port has drifted, regardless of what any round-trip test says: a
round trip passes happily against a scheme nobody else speaks.
"""

from __future__ import annotations

import os
import sys

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from nostr import crypto
from nostr.media.filecrypto import (
    ENVELOPE_VERSION,
    MAX_PLAINTEXT_BYTES,
    MIN_ENVELOPE_LEN,
    EncryptedFile,
    FileCryptoError,
    conversation_key_for,
    decrypt_file,
    encrypt_file,
    looks_encrypted,
)


# Generated by Node's WebCrypto using Lotus's exact derivation. Do not
# regenerate these to make a failing test pass: a mismatch means our
# construction moved, which is the failure this file exists to catch.
VECTOR_CONVERSATION_KEY = "1e" * 32
VECTOR_NONCE = "2b" * 32
VECTOR_PLAINTEXT = bytes.fromhex(
    "612074696e79207072697661746520706963747572652c207072657465"
    "6e64207468697320697320504e47206279746573"
)
VECTOR_ENVELOPE = bytes.fromhex(
    "022b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b"
    "063213a2e7f4115952b9f4b98d823fefe0a5e83f3b093d0cba1f57c2dad655f2a4"
    "68ad99a63e9604de2191a855042c5e189ce62fc2851c578fd2297703d32fdca7"
)


# --------------------------------------------------------------------- #
# Interoperability with Lotus                                           #
# --------------------------------------------------------------------- #

def test_a_lotus_written_envelope_decrypts_here():
    # The vector carries a conversation key directly rather than a file
    # key, since that is the layer where the two implementations meet.
    from nostr.media import filecrypto

    aes_key, iv = filecrypto._derive(
        bytes.fromhex(VECTOR_CONVERSATION_KEY), bytes.fromhex(VECTOR_NONCE),
    )
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    recovered = AESGCM(aes_key).decrypt(iv, VECTOR_ENVELOPE[33:], None)
    assert recovered == VECTOR_PLAINTEXT


def test_we_reproduce_the_vector_byte_for_byte():
    from nostr.media import filecrypto
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    aes_key, iv = filecrypto._derive(
        bytes.fromhex(VECTOR_CONVERSATION_KEY), bytes.fromhex(VECTOR_NONCE),
    )
    produced = AESGCM(aes_key).encrypt(iv, VECTOR_PLAINTEXT, None)
    assert bytes([ENVELOPE_VERSION]) + bytes.fromhex(VECTOR_NONCE) + produced == (
        VECTOR_ENVELOPE
    )


def test_the_envelope_layout_is_the_documented_one():
    out = encrypt_file(b"x" * 100)
    assert out.envelope[0] == ENVELOPE_VERSION
    # version + nonce + ciphertext + GCM tag
    assert len(out.envelope) == 1 + 32 + 100 + 16


def test_the_file_key_is_self_directed():
    # The key alone opens the file, so it can be shared without sharing
    # anything belonging to the account.
    out = encrypt_file(b"hello")
    secret = bytes.fromhex(out.key_hex)
    expected = crypto.conversation_key(secret, crypto.get_public_key(secret))
    assert conversation_key_for(out.key_hex) == expected


# --------------------------------------------------------------------- #
# Round trips                                                           #
# --------------------------------------------------------------------- #

@pytest.mark.parametrize("size", [0, 1, 15, 16, 17, 1024, 100_000])
def test_round_trip_at_various_sizes(size):
    data = os.urandom(size)
    out = encrypt_file(data)
    assert decrypt_file(out.envelope, out.key_hex) == data


def test_ciphertext_never_contains_the_plaintext():
    data = b"the account number is 12345" * 40
    out = encrypt_file(data)
    assert data not in out.envelope
    assert b"account number" not in out.envelope


def test_two_encryptions_of_the_same_bytes_differ():
    # A fresh key and nonce each time, so identical files do not reveal
    # that they are identical to whoever holds the blobs.
    data = b"same picture"
    a, b = encrypt_file(data), encrypt_file(data)
    assert a.envelope != b.envelope
    assert a.key_hex != b.key_hex


# --------------------------------------------------------------------- #
# Refusals                                                              #
# --------------------------------------------------------------------- #

def test_the_wrong_key_is_refused_rather_than_guessed_at():
    out = encrypt_file(b"private")
    other = encrypt_file(b"unrelated").key_hex
    with pytest.raises(FileCryptoError):
        decrypt_file(out.envelope, other)


def test_a_tampered_ciphertext_is_refused():
    out = encrypt_file(b"private bytes here")
    broken = bytearray(out.envelope)
    broken[-1] ^= 0x01
    with pytest.raises(FileCryptoError):
        decrypt_file(bytes(broken), out.key_hex)


def test_a_tampered_nonce_is_refused():
    out = encrypt_file(b"private bytes here")
    broken = bytearray(out.envelope)
    broken[5] ^= 0x01
    with pytest.raises(FileCryptoError):
        decrypt_file(bytes(broken), out.key_hex)


def test_an_unknown_version_is_named_rather_than_misread():
    out = encrypt_file(b"x")
    broken = bytearray(out.envelope)
    broken[0] = 9
    with pytest.raises(FileCryptoError, match="version"):
        decrypt_file(bytes(broken), out.key_hex)


@pytest.mark.parametrize("bad", [b"", b"\x02", b"\x02" + b"\x00" * 40])
def test_a_truncated_envelope_is_refused(bad):
    with pytest.raises(FileCryptoError):
        decrypt_file(bad, "aa" * 32)


@pytest.mark.parametrize("bad_key", ["", "zz" * 32, "aa" * 16, "aa" * 64])
def test_a_malformed_key_is_refused(bad_key):
    out = encrypt_file(b"x")
    with pytest.raises(FileCryptoError):
        decrypt_file(out.envelope, bad_key)


def test_an_oversized_file_is_refused_before_it_is_buffered():
    # Refusing beats being killed for memory halfway through a 1 GB file.
    class _Huge(bytes):
        def __len__(self):
            return MAX_PLAINTEXT_BYTES + 1

    with pytest.raises(FileCryptoError, match="limit"):
        encrypt_file(_Huge())


def test_non_bytes_input_is_refused():
    with pytest.raises(FileCryptoError):
        encrypt_file("a string is not bytes")


# --------------------------------------------------------------------- #
# Telling a private blob from a picture                                 #
# --------------------------------------------------------------------- #

def test_an_envelope_is_recognised():
    assert looks_encrypted(encrypt_file(b"x").envelope)


@pytest.mark.parametrize("magic", [
    b"\x89PNG\r\n\x1a\n" + b"\x00" * 40,        # PNG
    b"\xff\xd8\xff\xe0" + b"\x00" * 40,          # JPEG
    b"GIF89a" + b"\x00" * 40,                    # GIF
    b"RIFF" + b"\x00" * 40,                      # WebP container
    b"BM" + b"\x00" * 40,                        # BMP
])
def test_real_images_are_not_mistaken_for_envelopes(magic):
    assert not looks_encrypted(magic)


@pytest.mark.parametrize("junk", [b"", b"\x02", b"\x02\x00", None, "text"])
def test_short_or_wrong_input_is_not_an_envelope(junk):
    assert not looks_encrypted(junk)


def test_the_detector_is_only_a_hint():
    # Anything starting 0x02 and long enough passes, so this must never
    # be used to decide access, only what to show.
    assert looks_encrypted(b"\x02" + b"\x00" * MIN_ENVELOPE_LEN)
